---
- name: Install Ansible and configure SSH keys on slave node
  hosts: webservers
  become: true
  become_user: root
  tasks:
    - name: Install EPEL release
      dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        state: present

    - name: Enable EPEL repository
      command: dnf config-manager --set-enabled epel

    - name: Install Ansible
      dnf:
        name: ansible
        state: present

    - name: Check Ansible version
      command: ansible --version
      register: ansible_version

    - name: Show Ansible version
      debug:
        var: ansible_version.stdout_lines

    - name: Generate SSH key for shivanitejale4 (if not exists)
      become: true
      become_user: shivanitejale4
      openssh_keypair:
        path: /home/shivanitejale4/.ssh/id_rsa
        type: rsa
        size: 2048
        state: present

    - name: Ensure public key is in authorized_keys
      authorized_key:
        user: shivanitejale4
        state: present
        key: "{{ lookup('file', '/home/shivanitejale4/.ssh/id_rsa.pub') }}"
        manage_dir: yes
