---
- name: Install Ansible and configure SSH keys on slave node
  hosts: webservers
  become: true
  become_user: root
  tasks:
    - name: Install EPEL release
      dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        state: present

    - name: Enable EPEL repository
      command: dnf config-manager --set-enabled epel

    - name: Install Ansible
      dnf:
        name: ansible
        state: present

    - name: Check Ansible version
      command: ansible --version
      register: ansible_version

    - name: Show Ansible version
      debug:
        var: ansible_version.stdout

    - name: Generate SSH key (if not exists)
      openssh_keypair:
        path: /root/.ssh/id_rsa
        type: rsa
        size: 2048
        state: present

    - name: Copy SSH key to remote host
      authorized_key:
        user: shivani
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        manage_dir: yes
      delegate_to: 35.184.141.13
